# Generated by Django 2.0.13 on 2019-06-18 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=90)),
                ('receiver', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=90)),
                ('creation_date', models.DateTimeField(default='2019-06-18 12:54')),
                ('read_message', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
