# Generated by Django 2.0.13 on 2019-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_system', '0004_auto_20190702_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default='2019-07-02 13:43'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=150),
        ),
    ]
