# Generated by Django 2.0.13 on 2019-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_system', '0005_auto_20190702_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default='2019-07-02 17:24'),
        ),
    ]
